#!/bin/bash

subsFile="./subscribers" #DMR ID of end users (7 digits)        ##Sample content: 1107010,3161013,
regsFile="./registrants" #DMR ID + SSID of hotspots (9 digits)  ##Sample content: 110701001-110701099,316101301-316101399,
usersRadioIDFile="/opt/HBlink3/subscriber_ids.json"
subscribers=$(<$subsFile)
registrants=$(<$regsFile)
x=0

while [ $x -lt 2 ]
do

if grep -q "$1" "$usersRadioIDFile" #Checks to make sure DMR ID is valid from RadioID.net download
  then
    printf "\n\033[32;1mDMR ID found valid\033[0m\n\n"
    x=2

    if grep -q "$1" "$subsFile" #Checks to make sure the DMR ID does not already exist in the subscriber file before adding
      then
        printf "\n\033[31;1mDMR ID already exists in subscribers file\033[0m\n\n"
      else
        newSubs="$subscribers,$1"
        cat > $subsFile <<- EOF
	$newSubs
	EOF

        if grep -q "$1" "$subsFile" #Checks to make sure the DMR was added successfully
          then
            printf "\n\033[32;1mDMR ID added to the subscriber file sucessfully\033[0m\n\n"
          else
            printf "\n\033[31;1mThere was a problem adding the DMR ID to the subscribers file\033[0m\n\n"
          fi

      fi

    if grep -q "$101-$199" "$regsFile" #Checks to make sure DMR ID + SSID does not already exist in the registrants file before adding
      then
        printf "\n\033[31;1mDMR ID already exists in registrants file\033[0m\n\n"
      else
        newRegs="$registrants,$101-$199"
        cat > $regsFile <<- EOF
	$newRegs
	EOF

        if grep -q "$101-$199" "$regsFile" #Checks to make sure DMR ID + SSID was added successfully
          then
            printf "\n\033[32;1mDMR ID + SSID added to the registrants file sucessfully\033[0m\n\n"
          else
            printf "\n\033[31;1mThere was a problem adding the DMR ID + SSID to the registrants file\033[0m\n\n"
          fi

      fi

    if grep -q "$1" "$subsFile" && grep -q "$101-$199" "$regsFile" #Reminds user to restart service on successful update
      then
        printf "\e[0m\e[1;33mFor changes to take effect, please restart hblink.service by typing:\e[0m\n\t\e[1;36msystemctl restart hblink.service\e[0m\n\n"
      fi

  else
    x=$(( $x + 1 ))

    case $x
    in
      1)
        printf "\n\033[31;1mDownloading DMR ID List\033[0m\n\n"
        wget https://database.radioid.net/static/users.json -O $usersRadioIDFile
	sleep 5
        ;;
      2)
        printf "\n\033[31;1mDMR ID not found\033[0m\n\n"
        ;;
        esac
  fi

done
