#!/bin/bash

subsFile="./subscribers" #DMR ID of end users (7 digits)        ##Sample content: 1107010,3161013,
regsFile="./registrants" #DMR ID + SSID of hotspots (9 digits)  ##Sample content: 110701001-110701099,316101301-316101399,
subscribers=$(<$subsFile)
registrants=$(<$regsFile)

  if grep -q "$1" "$subsFile" #Checks to make sure the DMR ID exists before attempting to delete from subscriber file
    then
      sed -i -- "s/,$1//" $subsFile

      if grep -q "$1" "$subsFile" #Checks to make sure the DMR ID was removed successfully
        then
          printf "\n\033[31;1mThere was a problem removing the DMR ID to the subscribers file\033[0m\n\n"
        else
          printf "\n\033[32;1mDMR ID removed from the subscriber file sucessfully\033[0m\n\n"
        fi

    else
      printf "\n\033[31;1mDMR ID not found in subscribers file\033[0m\n\n"

    fi

  if grep -q "$101-$199" "$regsFile" #Checks to make sure the DMR ID exists before attempting to delete from registrants file
    then
      sed -i -- "s/,$101-$199//" $regsFile

      if grep -q "$1" "$regsFile" #Checks to make sure the DMR ID was removed successfully
        then
          printf "\n\033[31;1mThere was a problem removing the DMR ID to the registrants file\033[0m\n\n"
        else
          printf "\n\033[32;1mDMR ID removed from the registrants file sucessfully\033[0m\n\n"
        fi

    else
      printf "\n\033[31;1mDMR ID not found in registrants file\033[0m\n\n"
    fi

 if grep -q "$1" "$subsFile" && grep -q "$101-$199" "$regsFile" #Reminds user to restart service on successful update or troubleshoot
    then
      printf "\n\033[31;1mPlease check your permissions and try again\033[0m\n\n"
    else
      printf "\e[0m\e[1;33mFor changes to take effect, please restart hblink.service by typing:\e[0m\n\t\e[1;36msystemctl restart hblink.service\e[0m\n\n"
    fi

